version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template-file template.yaml --output-template-file template-out.yaml --s3-bucket rikesh-estiotest
  post_build:
    commands:
      - echo "Build and packaging completed successfully."
artifacts:
  files:
    - template.yaml
    - template-out.yaml
