version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r lambda.zip WeatherAPIAWS.py
artifacts:
  files:
    - lambda.zip
    - '**/*'
  discard-paths: yes
