Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.11
      CodeUri: ./
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get        
